### ISSUE TITLE
Percentage calculation issue

### ISSUE THREAD

**Issue by bbashy** [jeroennoten/laravel-poll#2]
1 vote on each 3 answers results in 33% != 100%

It's from the rounding, any solution?

**Comment by jeroennoten** [comment]
I don't really see the problem with this..?

**Comment by bbashy** [comment]
No, maybe not. There's no real solution for it I guess. 

Most polls just show 33% for each?

**Comment by jeroennoten** [comment]
Yeah.. what other options are there?
